app_job:
    path:     /
    defaults: { _controller: "AppJoboardBundle:Job:index" }

app_job_show:
    path:     /{company}/{location}/{id}/{position}/
    defaults: { _controller: "AppJoboardBundle:Job:show" }
    requirements:
            id:  \d+

app_job_new:
    path:     /new
    defaults: { _controller: "AppJoboardBundle:Job:new" }

app_job_create:
    path:     /create
    defaults: { _controller: "AppJoboardBundle:Job:create" }
    requirements: { _method: post }

app_job_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppJoboardBundle:Job:edit" }

app_job_update:
    path:     /{id}/update
    defaults: { _controller: "AppJoboardBundle:Job:update" }
    requirements: { _method: post|put }

app_job_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppJoboardBundle:Job:delete" }
    requirements: { _method: post|delete }
