app_joboard_app_job:
    resource: "@AppJoboardBundle/Resources/config/routing/job.yml"
    prefix:   /app_job

app_joboard_homepage:
    path:     /
    defaults: { _controller: AppJoboardBundle:Job:index }
AppJoboardBundle_job:
    resource: "@AppJoboardBundle/Resources/config/routing/job.yml"
    prefix: /job
